# Generated by Django 2.2.4 on 2019-09-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialupdate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
