# Generated by Django 2.2.4 on 2019-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialupdate', '0003_post_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.IntegerField(null=True),
        ),
    ]
