# Generated by Django 2.2.4 on 2019-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialupdate', '0005_auto_20190903_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
