# Generated by Django 2.2.4 on 2019-09-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialupdate', '0007_auto_20190903_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_img',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
