# Generated by Django 2.2.4 on 2019-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialupdate', '0008_auto_20190903_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_img',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
